AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'db/seeds.rb'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'
    - 'app/views/**/*'
